export const articles = {
    "Pizza slice": "🍕",
    "Doughnut": "🍩",
    "Lollipop": "🍭",
    "Rocket": "🚀",
    "Honeybee": "🐝",
    "Egg": "🥚",
    "Cupcake": "🧁",
    "Mushroom": "🍄",
    "Watermelon": "🍉",
    "Apple": "🍎",
    "Banana": "🍌",
    "Carrot": "🥕",
    "Sunflower": "🌻",
    "Rabbit": "🐇",
    "Dog": "🐕",
    "Sheep": "🐑",
    "Fish": "🐟",
    "Butterfly": "🦋",
};