import type { Subject, Course } from "../types/subject.types";

export const coursesData: Course[] = [
    {
        id: "general_clock",
        subjectId: "g.k",
        label: "What's the time?",
        description: "Can you read the clock?",
        image: "https://iili.io/FQh4m2R.jpg",
        route: "/general/clock",
        component: "clock",
    },
    {
        id: "general_identify_letter",
        label: "Identify the Letter",
        description: "Listen to letters and identify them from multiple choices",
        image: "🔤",
        route: "/general/identify-letter",
        component: "identify-letter",
        subjectId: "g.k",
    },
    {
        id: "hindi_counting",
        subjectId: "hindi",
        label: "हिंदी की गिनती",
        description: "क्या आपको हिंदी में गिनती आती है?",
        image: "https://iili.io/FZcEYNt.jpg",
        route: "/hindi/counting",
        component: "counting",
    },
    {
        id: "hindi_numbers",
        subjectId: "hindi",
        label: "हिंदी संख्या पहचानें (Numbers)",
        description: "0 से 1000 के बीच की हिन्दी संख्या पहचानें।",
        image: "https://iili.io/FZcEYNt.jpg",
        route: "/hindi/numbers",
        component: "numbers",
    },
    {
        id: "maths_counting_1_20",
        subjectId: "maths",
        label: "Counting (1-20)",
        image: "🔢",
        route: "/maths/counting-1-20",
        component: "counting-1-20",
        description: "How many are there?",
    },
    {
        id: "maths_identify_number",
        subjectId: "maths",
        description: "An interactive course for preschoolers to learn numbers by speech",
        image: "🔢",
        route: "/maths/identify-number",
        component: "identify-number",
        label: "Identify the Number by sound",
    },
    {
        id: "maths_tables",
        subjectId: "maths",
        label: "Multiplication Tables",
        description: "Learn and practice tables from 2 to 20.",
        image: "https://iili.io/FZl9DGV.jpg",
        route: "/maths/tables",
        component: "tables",
    },
    {
        id: "stem_units",
        subjectId: "stem",
        label: "Units of Measurement",
        description: "What category does this unit belong to?",
        image: "https://iili.io/FZlHtNs.jpg",
        route: "/stem/units",
        component: "units",
    },
    {
        id: "world_capitals_of_countries",
        subjectId: "world",
        label: "Capital Cities of Countries",
        description: "Do you know the capitals of different countries?",
        image: "https://iili.io/FZlBdAB.jpg",
        route: "/world/capitals-of-countries",
        component: "capitals-of-countries",
    },
    {
        id: "world_capitals_of_india",
        subjectId: "world",
        label: "Capital Cities of India",
        description: "Do you know the capitals of Indian states?",
        image: "https://iili.io/FZlBdAB.jpg",
        route: "/world/capitals-of-india",
        component: "capitals-of-india",
    },
    {
        id: "world_challenge_flags",
        subjectId: "world",
        label: "Challenge - Flags",
        description: "Test your flag knowledge! Identify 10 flags in 30 seconds",
        image: "🏆",
        route: "/world/challenge-flags",
        component: "challenge-flags",
    },
    {
        id: "world_flags_of_countries",
        subjectId: "world",
        label: "Flags of Countries",
        description: "Learn to identify flags of different countries",
        route: "/world/flags-of-countries",
        component: "flags-of-countries",
        image: "https://iili.io/FZlHtNs.jpg",
    },
];

export const subjectsData: Subject[] = [
    {
        id: "g.k",
        label: "Trivia",
        description: "Explore various topics in general knowledge.",
        route: "/general",
        icon: "twemoji:brain",
        bg: "#4b1212",
        shadow: "#C94B4B",
        rotate: "-3deg",
        courses: [],
    },
    {
        id: "stem",
        label: "STEM",
        description: "Explore basic science concepts and experiments.",
        route: "/stem",
        icon: "twemoji:microscope",
        bg: "#223f6d",
        shadow: "#2D6FD4",
        rotate: "3deg",
        courses: [],
    },
    {
        id: "maths",
        label: "Maths",
        description: "Learn basic mathematics concepts and operations.",
        route: "/maths",
        icon: "twemoji:input-numbers",
        bg: "#1e7962",
        shadow: "#2A9D7A",
        rotate: "-2deg",
        courses: [],
    },
    {
        id: "hindi",
        label: "Hindi",
        description: "Learn Hindi language basics, vocabulary, and grammar.",
        route: "/hindi",
        icon: "twemoji:diya-lamp",
        bg: "#c97c34",
        shadow: "#C97A20",
        rotate: "2deg",
        courses: [],
    },

    {
        id: "world",
        label: "World",
        description: "Learn about different cultures, geography, and history.",
        route: "/world",
        icon: "twemoji:globe-showing-asia-australia",
        bg: "#523e8f",
        shadow: "#7C5DC9",
        rotate: "-1deg",
        courses: [],
    },
];

// Build the combined data with courses attached to subjects
export const getCombinedSubjectsData = (): Subject[] => {
    return subjectsData.map((subject) => ({
        ...subject,
        courses: coursesData.filter((course) => course.subjectId === subject.id),
    }));
};
