import type { Subject, Course } from "../types/subject.types";
import { CourseCategory, SubjectId } from "../types/subject.types";

export const coursesData: Course[] = [
  {
    id: "maths_clock",
    subjectId: SubjectId.MATHS,
    label: "What's the time?",
    description: "Can you read the clock?",
    icon: "noto:four-thirty",
    route: "/maths/clock",
    component: "clock",
    category: CourseCategory.PRACTICE,
  },
  {
    id: "general_identify_letter",
    label: "Identify the Letter",
    description: "Listen to letters and identify them from multiple choices",
    icon: "noto:input-latin-uppercase",
    route: "/general/identify-letter",
    component: "identify-letter",
    subjectId: SubjectId.GENERAL,
    category: CourseCategory.PRACTICE,
  },
  {
    id: "hindi_counting",
    subjectId: SubjectId.HINDI,
    label: "हिंदी की गिनती",
    description: "क्या आपको हिंदी में गिनती आती है?",
    icon: "noto:victory-hand",
    route: "/hindi/counting",
    component: "counting",
    category: CourseCategory.LEARN,
  },
  {
    id: "hindi_numbers",
    subjectId: SubjectId.HINDI,
    label: "हिंदी संख्या पहचानें (Numbers)",
    description: "0 से 1000 के बीच की हिन्दी संख्या पहचानें।",
    icon: "twemoji:hand-with-fingers-splayed",
    route: "/hindi/numbers",
    component: "numbers",
    category: CourseCategory.PRACTICE,
  },
  {
    id: "maths_counting_1_20",
    subjectId: SubjectId.MATHS,
    label: "Counting (1-20)",
    icon: "noto:input-numbers",
    route: "/maths/counting-1-20",
    component: "counting-1-20",
    description: "How many are there?",
    category: CourseCategory.LEARN,
  },
  {
    id: "maths_identify_number",
    subjectId: SubjectId.MATHS,
    description:
      "An interactive course for preschoolers to learn numbers by speech",
    icon: "twemoji:input-numbers",
    route: "/maths/identify-number",
    component: "identify-number",
    label: "Identify the Number by sound",
    category: CourseCategory.PRACTICE,
  },
  {
    id: "maths_tables",
    subjectId: SubjectId.MATHS,
    label: "Multiplication Tables",
    description: "Learn and practice tables from 2 to 20.",
    icon: "twemoji:multiplication-sign",
    route: "/maths/tables",
    component: "tables",
    category: CourseCategory.PRACTICE,
  },
  {
    id: "stem_units",
    subjectId: SubjectId.STEM,
    label: "Units of Measurement",
    description: "What category does this unit belong to?",
    icon: "twemoji:input-symbols",
    route: "/stem/units",
    component: "units",
    category: CourseCategory.PRACTICE,
  },
  {
    id: "world_capitals_of_countries",
    subjectId: SubjectId.WORLD,
    label: "Capital Cities of Countries",
    description: "Do you know the capitals of different countries?",
    icon: "twemoji:classical-building",
    route: "/world/capitals-of-countries",
    component: "capitals-of-countries",
    category: CourseCategory.LEARN,
  },
  {
    id: "world_capitals_of_india",
    subjectId: SubjectId.WORLD,
    label: "Capital Cities of India",
    description: "Do you know the capitals of Indian states?",
    icon: "twemoji:building-construction",
    route: "/world/capitals-of-india",
    component: "capitals-of-india",
    category: CourseCategory.PRACTICE,
  },
  {
    id: "world_challenge_flags",
    subjectId: SubjectId.WORLD,
    label: "Challenge - Flags",
    description: "Test your flag knowledge! Identify 10 flags in 30 seconds",
    icon: "twemoji:trophy",
    route: "/world/challenge-flags",
    component: "challenge-flags",
    category: CourseCategory.CHALLENGE,
  },
  {
    id: "world_flags_of_countries",
    subjectId: SubjectId.WORLD,
    label: "Flags of Countries",
    description: "Learn to identify flags of different countries",
    route: "/world/flags-of-countries",
    component: "flags-of-countries",
    icon: "twemoji:waving-white-flag",
    category: CourseCategory.LEARN,
  },
];

export const subjectsData: Subject[] = [
  {
    id: SubjectId.GENERAL,
    label: "Trivia",
    description: "Explore various topics in general knowledge.",
    route: "/general",
    icon: "twemoji:brain",
    bg: "#4b1212",
    shadow: "#C94B4B",
    rotate: "-3deg",
    pageBackground: "#cdb4db",
    courses: [],
  },
  {
    id: SubjectId.STEM,
    label: "STEM",
    description: "Explore basic science concepts and experiments.",
    route: "/stem",
    icon: "twemoji:microscope",
    bg: "#223f6d",
    shadow: "#2D6FD4",
    rotate: "3deg",
    pageBackground: "#ffc8dd",
    courses: [],
  },
  {
    id: SubjectId.MATHS,
    label: "Maths",
    description: "Learn basic mathematics concepts and operations.",
    route: "/maths",
    icon: "twemoji:input-numbers",
    bg: "#1e7962",
    shadow: "#2A9D7A",
    rotate: "-2deg",
    pageBackground: "#ffafcc",
    courses: [],
  },
  {
    id: SubjectId.HINDI,
    label: "Hindi",
    description: "Learn & Practice Hindi language",
    route: "/hindi",
    icon: "noto:om",
    bg: "#c97c34",
    shadow: "#C97A20",
    rotate: "2deg",
    pageBackground: "#bde0fe",
    courses: [],
  },

  {
    id: SubjectId.WORLD,
    label: "World",
    description: "Learn about different cultures, geography, and history.",
    route: "/world",
    icon: "twemoji:globe-showing-asia-australia",
    bg: "#523e8f",
    shadow: "#7C5DC9",
    rotate: "-1deg",
    pageBackground: "#a2d2ff",
    courses: [],
  },
];

// Build the combined data with courses attached to subjects
export const getCombinedSubjectsData = (): Subject[] => {
  return subjectsData.map((subject) => ({
    ...subject,
    courses: coursesData.filter((course) => course.subjectId === subject.id),
  }));
};
