import type { Course } from "@/types/subject.types";
import { CourseCategory, SubjectId } from "@/types/subject.types";

export const mathsCourses: Course[] = [
    {
        id: "maths_basic_addition",
        subjectId: SubjectId.MATHS,
        label: "Basic Addition",
        description: "क्या आप जोड़ लगा सकते हैं?",
        icon: "noto:plus-button",
        route: "/maths/basic-addition",
        component: "addition",
        category: CourseCategory.PRACTICE,
    },
    {
        id: "maths_counting_1_20",
        subjectId: SubjectId.MATHS,
        label: "Counting 1 to 20",
        description: "Learn to count from 1 to 20",
        icon: "noto:keycap-1",
        route: "/maths/counting-1-20",
        component: "counting",
        category: CourseCategory.LEARN,
    },
    {
        id: "maths_identify_number",
        subjectId: SubjectId.MATHS,
        label: "Identify the Number",
        description: "Practice identifying numbers 1 to 100",
        icon: "noto:numbers",
        route: "/maths/identify-number",
        component: "identify-number",
        category: CourseCategory.PRACTICE,
    },
    {
        id: "maths_read_the_clock",
        subjectId: SubjectId.MATHS,
        label: "Read the Clock",
        description: "Learn to read time from an analog clock",
        icon: "noto:clock-face-one-oclock",
        route: "/maths/read-the-clock",
        component: "clock",
        category: CourseCategory.LEARN,
    },
    {
        id: "maths_learn_tables",
        subjectId: SubjectId.MATHS,
        label: "Learn Tables",
        description: "Learn multiplication tables 2 to 10",
        icon: "twemoji:multiplication-sign",
        route: "/maths/learn-tables",
        component: "tables",
        category: CourseCategory.LEARN,
    },
    {
        id: "maths_practice_tables",
        subjectId: SubjectId.MATHS,
        label: "Practice Tables",
        description: "Practice multiplication tables 2 to 10",
        icon: "twemoji:multiplication-sign",
        route: "/maths/practice-tables",
        component: "tables",
        category: CourseCategory.PRACTICE,
    },
];
